### ISSUE TITLE
About the verify method.

### ISSUE THREAD

**Issue by riquellopes** [mfuentesg/luhnpy#1]
Hi, 

I'm use the luhnpy package in my project. I've a question about the verify method. It return true when I check the number 0000000000000000. Is it should get True?

**Comment by mfuentesg** [comment]
Hey @riquellopes you can check that number using this page https://www.dcode.fr/luhn-algorithm.

To me `0000000000000000` it's a valid luhn number

**Comment by mfuentesg** [comment]
@riquellopes works?
